sfdc_conn_id:
  username: "bhargav.v@selectiva.com.dev"
  password: "AGTFfgtsde@1234"
  security_token: "mP7VTDKWfM7V6kvB7pPYJUBl"
  client_id: "3MVG9cyb9OsYZthKOXcu2NFtWLMxW6fYurZYrOQViZCUIPjlgxVBPSWdVE8JTYMRDqoTkV93Xaj81wtOqcNbh"
  client_secret: "0A97F80905F358EB04467A603E7458630D927BEFA46F500755252E84CCEBB97D"


another_sfdc_conn_id:
  username: "your_salesforce_username"
  password: "your_salesforce_password"
  security_token: "your_salesforce_security_token"
  client_id: "your_salesforce_client_id"
  client_secret: "your_salesforce_client_secret"



