sfdc_conn_id:
  username: "bhargav.v@selectiva.com"
  password: "AGTFfgtsde@1234"
  security_token: "99QGgvg0MJTK1NsALpSRXg16"
  client_id: "3MVG9XgkMlifdwVB60dyMz3jIc5E3QKxEemKvBq2SFoZgJ0QWZ0pP7Y8yulsw2t6i4O47sUXLt3awXekl_nIN"
  client_secret: "AFCC3C3C0ACC9E3B76DDEF9562C9C07F7856234A03826FF8D8C1E472F0E59101"

another_sfdc_conn_id:
  username: "your_salesforce_username"
  password: "your_salesforce_password"
  security_token: "your_salesforce_security_token"
  client_id: "your_salesforce_client_id"
  client_secret: "your_salesforce_client_secret"