postgresql_conn_id:
    engine: "postgresql"
    host: "localhost"
    port: "5432"
    dbname: "ELT"
    user: "stagereader"
    password: "elt-framework"
    driver: "org.postgresql.Driver"
    jdbc_url: "jdbc:postgresql://localhost:5432/postgres"

replication_config:
  config_dbname: "dbname"
  config_schema: "schema"
  config_table: "checkpoint"