postgresql_conn_id:
    engine: "postgresql"
    host: "localhost"
    port: "5432"
    dbname: "elt"
    user: "postgres"
    password: "123"
    driver: "org.postgresql.Driver"
    jdbc_url: "jdbc:postgresql://localhost:5432/postgres"