-- Create EDW Schema
CREATE SCHEMA IF NOT EXISTS sfdc_edw;


-- Account Table (EDW)
CREATE TABLE sfdc_edw.account (
    Id TEXT PRIMARY KEY,
    IsDeleted BOOLEAN,
    MasterRecordId TEXT,
    Name TEXT,
    Type TEXT,
    ParentId TEXT,
    BillingStreet TEXT,
    BillingCity TEXT,
    BillingState TEXT,
    BillingPostalCode TEXT,
    BillingCountry TEXT,
    BillingLatitude NUMERIC,
    BillingLongitude NUMERIC,
    BillingGeocodeAccuracy TEXT,
    BillingAddress TEXT,
    ShippingStreet TEXT,
    ShippingCity TEXT,
    ShippingState TEXT,
    ShippingPostalCode TEXT,
    ShippingCountry TEXT,
    ShippingLatitude NUMERIC,
    ShippingLongitude NUMERIC,
    ShippingGeocodeAccuracy TEXT,
    ShippingAddress TEXT,
    Phone TEXT,
    Fax TEXT,
    AccountNumber TEXT,
    Website TEXT,
    PhotoUrl TEXT,
    Sic TEXT,
    Industry TEXT,
    AnnualRevenue NUMERIC,
    NumberOfEmployees INTEGER,
    Ownership TEXT,
    TickerSymbol TEXT,
    Description TEXT,
    Rating TEXT,
    Site TEXT,
    OwnerId TEXT,
    CreatedDate TIMESTAMP WITH TIME ZONE,
    CreatedById TEXT,
    LastModifiedDate TIMESTAMP WITH TIME ZONE,
    LastModifiedById TEXT,
    SystemModstamp TIMESTAMP WITH TIME ZONE,
    LastActivityDate DATE,
    LastViewedDate TIMESTAMP WITH TIME ZONE,
    LastReferencedDate TIMESTAMP WITH TIME ZONE,
    Jigsaw TEXT,
    JigsawCompanyId TEXT,
    CleanStatus TEXT,
    AccountSource TEXT,
    DunsNumber TEXT,
    Tradestyle TEXT,
    NaicsCode TEXT,
    NaicsDesc TEXT,
    YearStarted TEXT,
    SicDesc TEXT,
    DandbCompanyId TEXT,
    CustomerPriority__c TEXT,
    SLA__c TEXT,
    Active__c TEXT,
    NumberofLocations__c INTEGER,
    UpsellOpportunity__c TEXT,
    SLASerialNumber__c TEXT,
    SLAExpirationDate__c DATE
);
