-- Inserting Values for Account Object in Salesforce 
-- Used to test and run the code 
INSERT INTO sfdc_ingestion_config.ing_tbl_list 
VALUES('account', 'sfdc_stage', 'account', 'True', 'LastModifiedDate');

INSERT INTO sfdc_ingestion_config.ing_tbl_columns
VALUES 
	('account', 'Id', 'account', 'Id', 'TEXT'),
	('account', 'IsDeleted', 'account', 'IsDeleted', 'TEXT'),
	('account', 'MasterRecordId', 'account', 'MasterRecordId', 'TEXT'),
	('account', 'Name', 'account', 'Name', 'TEXT'),
	('account', 'Type', 'account', 'Type', 'TEXT'),
	('account', 'ParentId', 'account', 'ParentId', 'TEXT'),
	('account', 'BillingStreet', 'account', 'BillingStreet', 'TEXT'),
	('account', 'BillingCity', 'account', 'BillingCity', 'TEXT'),
	('account', 'BillingState', 'account', 'BillingState', 'TEXT'),
	('account', 'BillingPostalCode', 'account', 'BillingPostalCode', 'TEXT'),
	('account', 'BillingCountry', 'account', 'BillingCountry', 'TEXT'),
	('account', 'BillingLatitude', 'account', 'BillingLatitude', 'TEXT'),
	('account', 'BillingLongitude', 'account', 'BillingLongitude', 'TEXT'),
	('account', 'BillingGeocodeAccuracy', 'account', 'BillingGeocodeAccuracy', 'TEXT'),
	('account', 'BillingAddress', 'account', 'BillingAddress', 'TEXT'),
	('account', 'ShippingStreet', 'account', 'ShippingStreet', 'TEXT'),
	('account', 'ShippingCity', 'account', 'ShippingCity', 'TEXT'),
	('account', 'ShippingState', 'account', 'ShippingState', 'TEXT'),
	('account', 'ShippingPostalCode', 'account', 'ShippingPostalCode', 'TEXT'),
	('account', 'ShippingCountry', 'account', 'ShippingCountry', 'TEXT'),
	('account', 'ShippingLatitude', 'account', 'ShippingLatitude', 'TEXT'),
	('account', 'ShippingLongitude', 'account', 'ShippingLongitude', 'TEXT'),
	('account', 'ShippingGeocodeAccuracy', 'account', 'ShippingGeocodeAccuracy', 'TEXT'),
	('account', 'ShippingAddress', 'account', 'ShippingAddress', 'TEXT'),
	('account', 'Phone', 'account', 'Phone', 'TEXT'),
	('account', 'Fax', 'account', 'Fax', 'TEXT'),
	('account', 'AccountNumber', 'account', 'AccountNumber', 'TEXT'),
	('account', 'Website', 'account', 'Website', 'TEXT'),
	('account', 'PhotoUrl', 'account', 'PhotoUrl', 'TEXT'),
	('account', 'Sic', 'account', 'Sic', 'TEXT'),
	('account', 'Industry', 'account', 'Industry', 'TEXT'),
	('account', 'AnnualRevenue', 'account', 'AnnualRevenue', 'TEXT'),
	('account', 'NumberOfEmployees', 'account', 'NumberOfEmployees', 'TEXT'),
	('account', 'Ownership', 'account', 'Ownership', 'TEXT'),
	('account', 'TickerSymbol', 'account', 'TickerSymbol', 'TEXT'),
	('account', 'Description', 'account', 'Description', 'TEXT'),
	('account', 'Rating', 'account', 'Rating', 'TEXT'),
	('account', 'Site', 'account', 'Site', 'TEXT'),
	('account', 'OwnerId', 'account', 'OwnerId', 'TEXT'),
	('account', 'CreatedDate', 'account', 'CreatedDate', 'TEXT'),
	('account', 'CreatedById', 'account', 'CreatedById', 'TEXT'),
	('account', 'LastModifiedDate', 'account', 'LastModifiedDate', 'TEXT'),
	('account', 'LastModifiedById', 'account', 'LastModifiedById', 'TEXT'),
	('account', 'SystemModstamp', 'account', 'SystemModstamp', 'TEXT'),
	('account', 'LastActivityDate', 'account', 'LastActivityDate', 'TEXT'),
	('account', 'LastViewedDate', 'account', 'LastViewedDate', 'TEXT'),
	('account', 'LastReferencedDate', 'account', 'LastReferencedDate', 'TEXT'),
	('account', 'Jigsaw', 'account', 'Jigsaw', 'TEXT'),
	('account', 'JigsawCompanyId', 'account', 'JigsawCompanyId', 'TEXT'),
	('account', 'CleanStatus', 'account', 'CleanStatus', 'TEXT'),
	('account', 'AccountSource', 'account', 'AccountSource', 'TEXT'),
	('account', 'DunsNumber', 'account', 'DunsNumber', 'TEXT'),
	('account', 'Tradestyle', 'account', 'Tradestyle', 'TEXT'),
	('account', 'NaicsCode', 'account', 'NaicsCode', 'TEXT'),
	('account', 'NaicsDesc', 'account', 'NaicsDesc', 'TEXT'),
	('account', 'YearStarted', 'account', 'YearStarted', 'TEXT'),
	('account', 'SicDesc', 'account', 'SicDesc', 'TEXT'),
	('account', 'DandbCompanyId', 'account', 'DandbCompanyId', 'TEXT'),
	('account', 'CustomerPriority__c', 'account', 'CustomerPriority__c', 'TEXT'),
	('account', 'SLA__c', 'account', 'SLA__c', 'TEXT'),
	('account', 'Active__c', 'account', 'Active__c', 'TEXT'),
	('account', 'NumberofLocations__c', 'account', 'NumberofLocations__c', 'TEXT'),
	('account', 'UpsellOpportunity__c', 'account', 'UpsellOpportunity__c', 'TEXT'),
	('account', 'SLASerialNumber__c', 'account', 'SLASerialNumber__c', 'TEXT'),
	('account', 'SLAExpirationDate__c', 'account', 'SLAExpirationDate__c', 'TEXT');

INSERT INTO sfdc_ingestion_config.ing_tbl_checkpoint
VALUES ('account', '1900-01-01 00:00:00 UTC');